/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as optionPositionSol from "./OptionPosition.sol";
export type { optionPositionSol };
import type * as mocks from "./mocks";
export type { mocks };
